# -*- coding: utf-8 -*-
"""Scraping_data_ulasan_gc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mAdn4L4grGNsIJtIFPd6fVGT6FkR15dc
"""

!pip install google-play-scraper

import csv
import pandas as pd
from datetime import datetime
from google_play_scraper import reviews_all, Sort

# Mengimpor pustaka google_play_scraper untuk mengakses ulasan dan informasi aplikasi dari Google Play Store.
from google_play_scraper import app, reviews_all, Sort

# Mengambil semua ulasan dari aplikasi dengan  ID 'com.byu.id' di Google Play Store.
# Proses scraping mungkin memerlukan beberapa saat tergantung pada jumlah ulasan yang ada.
scrapreview = reviews_all(
    'com.google.android.apps.classroom', # ID aplikasi
    lang='en', # Bahasa ulasan (default: 'en')
    country='us', # Negara (default: 'us')
    sort=Sort.MOST_RELEVANT, # Urutan ulasan (default: Sort.MOST_RELEVANT)
    count=5000 # Jumlah maksimum ulasan yg ingin diambil
)

app_reviews_df = pd.DataFrame(scrapreview)

app_reviews_df.to_csv('ulasan_aplikasi.csv', index=False)